### ISSUE TITLE
can't login to cloud

### ISSUE THREAD

**Issue by reidrichardson** [univ-of-utah-marriott-library-apple/recce#1]
The app seems to force the addition of :8443 if it is not included in the "hosts" string of the config file.  This seemingly makes it not work with a jamfcloud instance.  Log:

> 2019-07-19 11:23:00,584 - INFO - recce launched.
> 2019-07-19 11:23:00,584 - INFO - recce version 1.0
> 2019-07-19 11:23:00,584 - INFO - jss_login version 1.1
> 2019-07-19 11:23:00,584 - INFO - windows_computer version 1.0.2
> 2019-07-19 11:23:00,662 - INFO - read_create_prefs: activated
> 2019-07-19 11:23:00,662 - INFO - Configuration path: C:\ProgramData\edu.scl.utah.recce\edu.scl.utah.recce.ini
> 2019-07-19 11:23:00,662 - INFO - try_login: activated
> 2019-07-19 11:23:00,662 - INFO - call_jss: activated
> 2019-07-19 11:23:00,677 - INFO - call_jss called with accounts
> 2019-07-19 11:23:42,740 - ERROR - call_jss: Error contacting JSS: https://tenant_name.jamfcloud.com:8443
> 2019-07-19 11:23:42,756 - ERROR - call_jss: Exiting, Error calling accounts
>

**Comment by lazymutt** [comment]
**Thanks for trying Recce!**

Interesting. We don't have a cloud instance to test with. Let me do a bit of research on cloud instances and correct this issue as soon as possible.

**Comment by reidrichardson** [comment]
I think the issue could be as easy as altering line 85 of jss_login.py.  If I am reading the code correctly, it is automatically appending 8443 to any URL entered without it.  I'm curious if leaving off the +8443 portion of the line would make the connection to a cloud instance work.  
I tried to edit and compile it myself, but the corporate firewall did not like pip-win and quarantined it as a virus.

**Comment by lazymutt** [comment]
That's my thinking as well, checking for jamfcloud in the url.

**Comment by lazymutt** [comment]
@reidrichardson If you wouldn't mind being a guinea pig and testing my changes, I'd be eternally grateful. :)
